[project]
name = "slitherlink-solver"
version = "0.1.0"
description = "Formalizacao do Slitherlink em SAT com refinamento de subtours"
readme = "README.md"
authors = [
    { name = "Arthur Oliveira", email = "arthur12.2007g@gmail.com" },
    { name = "Joao Caique", email = "114672278+kaypes@users.noreply.github.com" },
    { name = "Gustavo Alexandre dos Santos", email = "santos.ag.dev@gmail.com" },
]
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.8",
]
